### ISSUE TITLE
laravel-sepa-xml for Laravel11

### ISSUE THREAD

**Issue by alex-inbase** [DREI-D/laravel-sepa-xml#4]
Moin Moin,
wäre es möglich laravel-sepa-xml auch für Laravel11 freizugeben?
Laut Beschreibung ist das Paket für Laravel 10 or higher, aber in composer.json ist "laravel/framework": "^10" !
Vielen Dank im Voraus und Grüße aus HH
Alex

**Comment by vollborn** [comment]
Moin Alex!

Hoppla, das habe ich übersehen. Bei mir hat auch unter Laravel 11 alles funktioniert, ich habe es eben mit in die Liste aufgenommen.

Beste Grüße
Olli

**Comment by alex-inbase** [comment]
Klasse! Vielen Dank!!!
